### ISSUE TITLE
remove "hello brewser" console log

### ISSUE THREAD

**Issue by ruffle1986** [robpataki/brewser#1]
I'd like to use brewser in production but I don't like the "hello brewser" console.log. I think it's too pushy. :(
If you don't mind, could you please remove it?

**Comment by robpataki** [comment]
Fair point, would you mind making a pull request with the updates? I am pretty busy at the moment, so I only will be able to do it myself in a few days time.

**Comment by ruffle1986** [comment]
@robertpataki of course!

**Comment by robpataki** [comment]
Nice one @ruffle1986!

**Comment by ruffle1986** [comment]
@robertpataki done #2

**Comment by robertpataki** [comment]
Hi @ruffle1986 - thanks for your updates, I've merged your pull request and published (v0.4.1)[https://github.com/handcraftedLDN/brewser/releases/tag/v0.4.1].

**Comment by robpataki** [comment]
Hi @ruffle1986 - thanks for your updates, I've merged your pull request and published [v0.4.1](https://github.com/handcraftedLDN/brewser/releases/tag/v0.4.1). I also updated the [Demo page](http://handcraftedldn.github.io/brewser/), where you can check the updates.
