### ISSUE TITLE
linter tool and tests are needed!

### ISSUE THREAD

**Issue by ruffle1986** [robpataki/brewser#3]
I use [xo](https://www.npmjs.com/package/xo) (it's on top of `eslint`) for linting and [ava](https://www.npmjs.com/package/ava)  (it's similar to `tape`) for testing. We have to use them or other tools otherwise contributing is going to be a nightmare.

**Comment by robpataki** [comment]
I had a look at XO, and it seems working somewhat better than JSHint (already included in the repo). I am happy to use XO for linting, but after making the code XO compliant I'll need to do some testing on the code to make sure nothing is broken - and this leads to your other suggestion regarding testing.

At this stage I am unsure whether introducing tests would be a benefit, as most of the code heavily relies on browser capabilities and user agent strings, so I don't see how mocking those would be any useful.

I would love to hear your thoughts on the testing aspects.

As soon as I'm done with implementing XO and testing the code I'll release a new version of brewser.

**Comment by ruffle1986** [comment]
Great! :+1: I'll be back soon with testing ideas.

**Comment by robpataki** [comment]
The XO implementation is on [develop](https://github.com/handcraftedLDN/brewser/tree/develop) branch at the moment BTW.

**Comment by robpataki** [comment]
Hey @ruffle1986. Any ideas on the tests? Any suggestions are welcome :)

**Comment by ruffle1986** [comment]
hey @robertpataki sorry for the disappearing. I didn't forget you. :) before the weekend I'll try to come up w/ something I can show you.
