### ISSUE TITLE
No 0.5.0 tag, bower throws error

### ISSUE THREAD

**Issue by mikegioia** [robpataki/brewser#5]
When specifying 0.5.0 in the bower.json, Brewser fails to download. I think you just need the 0.5.0 tag on the most recent commit.

**Comment by robpataki** [comment]
Hi @mikegioia, apologies for my sloppiness, I just pushed the 2 latest tags:
- https://github.com/handcraftedLDN/brewser/releases/tag/v0.4.3
- https://github.com/handcraftedLDN/brewser/releases/tag/v0.5.0

Bower should be happy now :)

Many thanks!

**Comment by mikegioia** [comment]
Thanks, Robert!
