### ISSUE TITLE
Using in vanilla code?

### ISSUE THREAD

**Issue by bfalchuk** [robpataki/brewser#9]
Hi, interesting and probably useful. But how can i use without frameworks or NPM in just vanilla codebases? In your demo i see you included brewser.min.js but its not built in the codebase.

**Comment by robpataki** [comment]
I am currently updating this repo, so various project types will be supported, including vanilla js and a hook for React TypeScript. In the meantime the NPM package can be used, but if you just want to pull in the minified file without having to deal with a package manager, you can load the minified script from https://unpkg.com/brewser@0.5.1/dist/brewser.js.

**Comment by robpataki** [comment]
Once you played with the library, I appreciate any feedback you may have.
